-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 17:47:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ff_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ff_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ff_database` DEFAULT CHARACTER SET utf8 ;
USE `ff_database` ;

-- -----------------------------------------------------
-- Table `ff_database`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` TINYTEXT NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  `post_date` DATETIME NOT NULL,
  `found_date` DATETIME NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NULL,
  `keywords` TINYTEXT NULL,
  `summary` TEXT NULL,
  `text` TEXT NOT NULL,
  `top_image` VARCHAR(45) NULL,
  `video` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `person_id` VARCHAR(45) NOT NULL,
  `party` VARCHAR(45) NOT NULL,
  `role` VARCHAR(255) NOT NULL COMMENT 'Could include: \nSenators\nHouse representative\nGovernor\nSenators to the national senate\nRepresentatives to the national senate\nOther roles…… ect',
  `legislative_since` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `biography` TEXT NULL,
  `district` VARCHAR(45) NULL,
  `counties` TINYTEXT NULL,
  `profession` VARCHAR(255) NULL,
  `profession_affiliations` TEXT NULL,
  `education` VARCHAR(255) NULL,
  `recognitions_and_honors` TEXT NULL,
  `home_phone` VARCHAR(45) NULL,
  `work_phone` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NULL,
  `mailing_address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `social_media` TINYTEXT NULL,
  `legislation_link` VARCHAR(255),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`article_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`article_person` (
  `articles_id` INT NOT NULL,
  `people_id` INT NOT NULL,
  `weight` INT NULL,
  `name_mentions` INT NOT NULL,
  `mention_percentage` INT NOT NULL,
  `article_total_count_mentions` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `people_id`),
  INDEX `fk_article_person_articles_idx` (`articles_id` ASC),
  INDEX `fk_article_person_people1_idx` (`people_id` ASC),
  CONSTRAINT `fk_article_person_articles`
    FOREIGN KEY (`articles_id`)
    REFERENCES `ff_database`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_person_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `ff_database`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`bills` (
  `bill_name_id` INT NOT NULL COMMENT 'such as HB306…..\n',
  `bill_type` VARCHAR(45) NOT NULL COMMENT 'HB: house bill\nHCR: House Concurrent Resolutions\nHJR: House Joint Resolutions\nHR: House Resolutions\nSB: Senate Bills\nSCR: Senate Concurrent Resolutions\nSJR: Senate Joint Resolutions\nSR: Senate Resolutions',
  `sponser` VARCHAR(45) NULL,
  `floor_sponser` VARCHAR(45) NULL,
  `substitute_sponser` VARCHAR(45) NULL,
  `last_action` VARCHAR(45) NULL,
  `last_location` VARCHAR(45) NULL,
  `text` TEXT NULL,
  PRIMARY KEY (`bill_name_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`bill_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`bill_status` (
  `bills_bill_name_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `vote` VARCHAR(255) NULL,
  `who_acted` VARCHAR(255) NULL COMMENT '• Senate Actions \n• House Actions \n• Fiscal Actions \n• Other Actions',
  PRIMARY KEY (`bills_bill_name_id`),
  INDEX `fk_bill_status_bills1_idx` (`bills_bill_name_id` ASC),
  CONSTRAINT `fk_bill_status_bills1`
    FOREIGN KEY (`bills_bill_name_id`)
    REFERENCES `ff_database`.`bills` (`bill_name_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`article_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`article_bill` (
  `articles_id` INT NOT NULL,
  `bills_bill_name_id` INT NOT NULL,
  `weight` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `bills_bill_name_id`),
  INDEX `fk_article_bill_bills1_idx` (`bills_bill_name_id` ASC),
  CONSTRAINT `fk_article_bill_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `ff_database`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_bill_bills1`
    FOREIGN KEY (`bills_bill_name_id`)
    REFERENCES `ff_database`.`bills` (`bill_name_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`person_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`person_bill` (
  `people_id` INT NOT NULL,
  `bills_bill_name_id` INT NOT NULL,
  PRIMARY KEY (`people_id`, `bills_bill_name_id`),
  INDEX `fk_person_bill_bills1_idx` (`bills_bill_name_id` ASC),
  CONSTRAINT `fk_person_bill_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `ff_database`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_bill_bills1`
    FOREIGN KEY (`bills_bill_name_id`)
    REFERENCES `ff_database`.`bills` (`bill_name_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`location` (
  `idlocations` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlocations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`article_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`article_location` (
  `articles_id` INT NOT NULL,
  `location_idlocations` INT NOT NULL,
  `weight` INT NULL,
  `location_mentions` INT NOT NULL,
  `mention_percentage` INT NOT NULL,
  `place_mention_total` INT NULL,
  PRIMARY KEY (`articles_id`, `location_idlocations`),
  INDEX `fk_article_location_location1_idx` (`location_idlocations` ASC),
  CONSTRAINT `fk_article_location_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `ff_database`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_location_location1`
    FOREIGN KEY (`location_idlocations`)
    REFERENCES `ff_database`.`location` (`idlocations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`article_based_weights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`article_based_weights` (
  `articles_id` INT NOT NULL,
  `length` INT NULL,
  `source_size_ratio` VARCHAR(255) NULL,
  `is_local` VARCHAR(45) NULL,
  PRIMARY KEY (`articles_id`),
  INDEX `fk_article_weights_articles1_idx` (`articles_id` ASC),
  CONSTRAINT `fk_article_weights_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `ff_database`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`committies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`committies` (
  `idcommitties` INT NOT NULL AUTO_INCREMENT,
  `committie` VARCHAR(255) NOT NULL,
  `overview` TEXT NULL,
  PRIMARY KEY (`idcommitties`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`person_committies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`person_committies` (
  `people_id` INT NOT NULL,
  `committies_idcommitties` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`people_id`, `committies_idcommitties`),
  INDEX `fk_person_committies_committies1_idx` (`committies_idcommitties` ASC),
  CONSTRAINT `fk_person_committies_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `ff_database`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_committies_committies1`
    FOREIGN KEY (`committies_idcommitties`)
    REFERENCES `ff_database`.`committies` (`idcommitties`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`bill_weight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`bill_weight` (
  `article_bill_articles_id` INT NOT NULL,
  `article_bill_bills_bill_name_id` INT NOT NULL,
  `bill_mentions` INT NOT NULL,
  `mention_percentage` INT NOT NULL,
  PRIMARY KEY (`article_bill_articles_id`, `article_bill_bills_bill_name_id`),
  CONSTRAINT `fk_bill_weight_article_bill1`
    FOREIGN KEY (`article_bill_articles_id` , `article_bill_bills_bill_name_id`)
    REFERENCES `ff_database`.`article_bill` (`articles_id` , `bills_bill_name_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ff_database`.`social_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ff_database`.`social_media` (
  `article_based_weights_articles_id` INT NOT NULL,
  `facebook_shares` INT NULL,
  `facebook_comments` INT NULL,
  `reddit_shares` INT NULL,
  `reddit_upvotes` INT NULL,
  `pinterest_pins` INT NULL,
  `linkedIn_shares` INT NULL,
  `total_count` INT NULL,
  PRIMARY KEY (`article_based_weights_articles_id`),
  CONSTRAINT `fk_social_media_article_based_weights1`
    FOREIGN KEY (`article_based_weights_articles_id`)
    REFERENCES `ff_database`.`article_based_weights` (`articles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
